on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello

  bar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
